### PR TITLE
Final-hawk consolidation

### PR DESCRIPTION
**Pull request by jokob-sk**

### CODE REVIEW

**Comment by Final-Hawk** [comment]
Thanks for merging! Hopefully everything works well.

**Comment by jokob-sk** [comment]
thanks for all the hard work! 💪based on the code changes, everything should be OK, but I'll do some testing before merging it into the main branch, just to be sure + I'll have a look at leiweibou changes

**Comment by Final-Hawk** [comment]
All good! Definitely with the testing, I was also doing some. Only issue I came across are the ones reported and another one. Still need to create a report and have a look though, but it was there before my changes anyway. When using the arrows on the device details page, the sessions, presence, and events tab do not update to the details of the newly selected device.

**Review by leiweibau — COMMENTED** [review]
works

**Comment by terorero** [comment]
Pi.Alert rules..!!!

**Pull request merged**
