### PR TITLE
feat: add pushover support

### PR DESCRIPTION
**Pull request by phynias**
adding support for pushover.net notifications.

### CODE REVIEW

**Comment by jokob-sk** [comment]
Thanks for the PR!

Can you please roll back all formatting changes to the `pialert.py` file? I won't be able to effectively review 1000+ line changes.

**Comment by dn4hc** [comment]
Looking forward to pushover support.

**Comment by jokob-sk** [comment]
You can use the Apprise integration as an interface for it I think. Adding new notifications is not high priority for me.

**Comment by jokob-sk** [comment]
No activity > closing

**Pull request closed without merging**
