### PR TITLE
Added the new "System Info" menu and various fixes for the new menu

### PR DESCRIPTION
**Pull request by cvc90**
<h1>Pull Request</h1>
<h2>Changes</h2>
<h3>Update header.php</h3>

- Add new menu System Info

<h3>Create and Update systeminfo.php</h3>

- Create page for the new "System Information" menu
- Updated OS-Version comment
- Updated blanks
- Update variable lang  <?= lang('SYSTEM_TITLE') ;?>
- Update variable lang  <?= lang('SYSTEM_TITLE') ;?>
- Fix variable $memory_usage_percent
- Fix variable 'mem_used'
- Add new content to the "Services" submenu
- Add new content to the "USB" variables submenu
- Add new content to the "USB" submenu
- Add new content to the "Storage" submenu
- Fixed comment space located in variable error_reporting(0); // Turn off php errors
- Added new content to the "Network Hardware" submenu
- Added new section of variables "Network Hardware stat"
- Updated some comments of variable sections
- Added final section separator
- Fixed end of submenu section
- Fixed Server name query

<h3>Update es_es.json</h3>

- Added new translation to Spanish, variable Navigation_SystemInfo" : "Información del sistema"
- Added new translation to Spanish, variable "SYSTEM_TITLE" : "Información del sistema"

<h3>Update en_us.json</h3>

- Added new translation to English, variable "Navigation_SystemInfo" : "System Information"
- Added new translation to English, variable "SYSTEM_TITLE" : "System Information"

<h3>Update de_de.json</h3>

- Added new translation to German, variable "Navigation_SystemInfo" : "Systeminformationen"
- Added new translation to German, variable "SYSTEM_TITLE" : "Systeminformationen"

<h3>Update Dockerfile</h3>

- Fixes for the new System Info menu to work in Docker, added "systemctl", "lsusb" to the installation list
- Change "lsusb" to "usbutils" in apt-get install

### CODE REVIEW

**Review by jokob-sk — CHANGES_REQUESTED** [review]
Can you move the link to the new Systeminfo page from the Maintenance page and remove it from the header.php. I really want the main menu to be reserved for Alert & Network functionality. It would be wonderful if we could consider placing the link as either a tab in maintenance or a simple link somewhere in the maintenance section. Thank you so much for your help!

**Comment by cvc90** [comment]
I will study what you say, but putting it in a tab in "Maintenance" with so much information available in this new menu, I thought that it was too overloaded in terms of design and that it was not the right place.

**Comment by jokob-sk** [comment]
Hummm, okay, let's keep it as it is for now. I was checking AdminLTE and v2 doesn't have Treeview, which would be ideal (expand collapse a submenu). Ideally I would upgrade to AdminLTE 3 but that's too much work right now.

https://adminlte.io/themes/v3/pages/UI/navbar.html

image

**Comment by jokob-sk** [comment]
Maybe let's rename to `System info` or `Hardware` so is not clipped
image

**Comment by cvc90** [comment]
Ok no problem, I change it to "System info".

**Comment by jokob-sk** [comment]
@cvc90 

The System info page shows some PHP errors, can you fix them?

```
Notice: A non well formed numeric value encountered in /home/pi/pialert/front/systeminfo.php on line 67

Warning: Use of undefined constant bc - assumed 'bc' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/systeminfo.php on line 67

Warning: A non-numeric value encountered in /home/pi/pialert/front/systeminfo.php on line 67
```

image

**Pull request merged**
