### PR TITLE
Added the new "Report" menu and various fixes for the new menu

### PR DESCRIPTION
**Pull request by cvc90**
<h1>Pull Request</h1>
<h2>Changes</h2>
<h3>Update header.php</h3>

- Added new menu "Report"

<h3>Create report.php</h3>

- Added new page "Report.php" to load the last report generated by Pi.Alert

<h3>Update es_es.json</h3>

- Added variable "Navigation_Report"
- Added variable "REPORT_TITLE"
- Added variable "REPORT_ERROR"

<h3>Update en_us.json</h3>

- Added variable "Navigation_Report"
- Added variable "REPORT_TITLE"
- Added variable "REPORT_ERROR"

<h3>Update de_de.json</h3>

- Added variable "Navigation_Report"
- Added variable "REPORT_TITLE"
- Added variable "REPORT_ERROR"

### CODE REVIEW

**Comment by leiweibau** [comment]
The Reports page alone, has little use. For this, things in the backend and parameters from the configuration file are still necessary.

**Comment by cvc90** [comment]
I'm sorry you don't agree with what you say, it seems to me a very useful page, it serves to review the last report generated and have an even faster and more accurate visualization of the last movements in the network.

**Comment by leiweibau** [comment]
No need to apologize 👍

**Comment by cvc90** [comment]
@jokob-sk Can you accept it?

**Pull request merged**
