### PR TITLE
Add missing german translations

### PR DESCRIPTION
**Pull request by lorki97**
This PR adds currently missing or mistranslated (Google Translate?) german translations to PiAlert. Work in Progress, draft created just as FYI for other maintainers to know that this is worked on.

I've seen https://github.com/jokob-sk/Pi.Alert/pull/464 only after already opening this draft PR. My PR plans to add all missing translations, especially in the settings page.

### CODE REVIEW

**Comment by jokob-sk** [comment]
I'm moving the publishers (NTFY, SMTP, MQTT, Apprise etc) into plugins so it's suggest to skip those settings for now. You can have a look at the other plugins missing German translations if interested

**Comment by jokob-sk** [comment]
The translations of plugins are in the config.json of a given plugin

**Comment by lorki97** [comment]
I guessed so based on our conversation in the feature request issue. Consolidating the plugins and making them more "standalone" is a good idea.

**Comment by jokob-sk** [comment]
No formatting guide, happy if you want to do it. My vs code instance doesn't seem to be fixing it.

**Comment by jokob-sk** [comment]
Hi @lorki97 - could I merge your changes in before I touch any of the config files? There is this bug report about the PIHOLE requiring SQL changes in the `config.json` file: https://github.com/jokob-sk/Pi.Alert/issues/479

**Comment by lorki97** [comment]
You can merge it, I'll open a second PR with the remaining changes based on the newest code.

**Pull request merged**
