### PR TITLE
Un-Discoverable Devices Plugin

### PR DESCRIPTION
**Pull request by Data-Monkey**
I have tested the plugin and run it for a few hours. 
Let me know if you need me to do some more testing or if I can help with your testing.
Hope this helps someone else out.

### CODE REVIEW

**Comment by Data-Monkey** [comment]
Sorry, the DB file should not be in this commit, I don't think so. How do I get it out I need to investigate...

**Comment by jokob-sk** [comment]
Nice work! Will have a look at this over the weekend probably.

**Comment by jokob-sk** [comment]
@Data-Monkey let me know once this is ready to be merged/tested

**Comment by Data-Monkey** [comment]
If you can merge it without the DB it is good to go. Not sure how I can undo the DB in my commit.

**Comment by jokob-sk** [comment]
I'll merge and re-add the db.

The whole DB folder is in gitignore already as far as I can tell:

https://github.com/jokob-sk/Pi.Alert/blob/422997be9b3d656468d7edd94c081148a8d02984/.gitignore#LL4C1-L4C5

**Comment by jokob-sk** [comment]
Great job on the plugin and documentation. Looks like there are no apparent issues so far, but let's see after the release, people always find something 😅

**Comment by jokob-sk** [comment]
I really like how you extracted the objects into the plugin_helper.py script, much better now. I might need to rewrite the older plugins in the future.

**Comment by jokob-sk** [comment]
OK, moved the helper into th eparent directory and made recommended it for new plugins going forward: https://github.com/jokob-sk/Pi.Alert/tree/main/front/plugins#-python-scriptpy-tips

**Comment by Data-Monkey** [comment]
that is great. That was my intention but I thought to stick to my own directory for now. 
I also started breaking out pyalert.py into modules as an exercise for myself. Is that something you would be interested in?

**Comment by jokob-sk** [comment]
@Data-Monkey Oh definitely. It is on my to-do list just didn't get to actually doing it. If you want to have a crack at it please do and I'll refrain from touching pialert.py for the next week.

**Comment by Data-Monkey** [comment]
I am not sure how quickly I can make it work. I started here. Working my way down the script ....
https://github.com/Data-Monkey/Pi.Alert/tree/split_it_up
so far I made it to the checkPermissionsOK() step

**Comment by jokob-sk** [comment]
no worries if it takes longer, happy to delay other work/release if it means the app will be easier to maintain going forward 👍 
Thanks for the help!

**Comment by Data-Monkey** [comment]
made some progress but had to leave some globals there that need to come out.
Have a look if that is something useful, it is a lot of work and even harder to test ...

**Comment by Data-Monkey** [comment]
Hi Jakob,
Should we start a new discussion for this?
I was wondering why there are so many commits in the code? Usually only write transactions require a commit?

**Comment by jokob-sk** [comment]
Feel free to open a new discussion/pr.

Re commits - mostly legacy code. Didn't remove them so I don't break stuff.

You should have seen all the connection open/closes there were before in the code I removed them.

**Pull request merged**
