### PR TITLE
Modified the style of the reports

### PR DESCRIPTION
**Pull request by cvc90**
<h1>Pull Request</h1>
<h2>Changes</h2>
<h3>Update report_template.html</h3>

- Modified creator banner url repot_template.html --> report_template.html
- Modified the creators banner adding to cvc90
- Removed several white spaces between banner and <html> tag
- Changed the background color in the table (bgcolor=#00c0ef --> bgcolor=#4b99d3)
- Changed the color of the text to white in the table (bgcolor=#ffffff --> bgcolor=#4b99d3)
- Changed the background color in td (bgcolor=#F5F5F5 --> bgcolor=#F1F5F5)
- Changed the background color in the footer table (bgcolor=#46802e --> bgcolor=#3c8dbc)
- Added in the footer table the color of the text to white (color: white)
- Changed footer text

<h3>Update report_template_new_version.html</h3>

- Modified creator banner url repot_template.html --> report_template_new_version.html
- Modified the creators banner adding to cvc90
- Removed several white spaces between banner and <html> tag
- Changed the background color in the table (bgcolor=#00c0ef --> bgcolor=#4b99d3)
- Changed the color of the text to white in the table ( bgcolor=#4b99d3 --> bgcolor=#ffffff)
- Changed the background color in td (bgcolor=#F5F5F5 --> bgcolor=#F1F5F5)
- Changed the background color in the footer table (bgcolor=#46802e --> bgcolor=#3c8dbc)
- Added in the footer table the color of the text to white (color: white)
- Changed footer text

<h3>Update reporting.py</h3>

- Added creator banner
- Added import const
- Changed color in headerProps variable (color:blue --> color:white)
- Modified bgcolor in headerProps variable (bgcolor=#909090 --> bgcolor=#64a0d6)
- Modified bgcolor in the thProps variable (bgcolor=#909090 --> bgcolor=#64a0d6)

### CODE REVIEW

**Comment by jokob-sk** [comment]
It looks like yo are still working on it @cvc90 ? I don't see where BUILD_PIALERT is replaced?

**Comment by cvc90** [comment]
The first part of the design is already finished, you can accept it. The second part will be in another PR that will provide the functionality to replace these two new labels introduced.

**Comment by jokob-sk** [comment]
Okay, @cvc90 , thanks 👍 I will merge this one, but in next PRs it's easier to test if the feature is complete - if that's possible going forward? 🙏

**Comment by jokob-sk** [comment]
Had to revert:

```bash

pialert    |   File "/home/pi/pialert/pialert/reporting.py", line 1
pialert    |     <!-- ---------------------------------------------------------------------------
pialert    |     ^
pialert    | SyntaxError: invalid syntax
pialert    | mkdir: cannot create directory '/run/php': File exists
pialert    | Starting nginx: nginx.
pialert    | Traceback (most recent call last):
pialert    |   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
pialert    |     return _run_code(code, main_globals, None,
pialert    |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
pialert    |     exec(code, run_globals)
pialert    |   File "/home/pi/pialert/pialert/__main__.py", line 29, in <module>
pialert    |     from networkscan import process_scan, scan_network
pialert    |   File "/home/pi/pialert/pialert/networkscan.py", line 10, in <module>
pialert    |     from reporting import skip_repeated_notifications
pialert    |   File "/home/pi/pialert/pialert/reporting.py", line 1
pialert    |     <!-- ---------------------------------------------------------------------------
pialert    |     ^
pialert    | SyntaxError: invalid syntax

```

please restart the app and test these changes so this is caught sooner 🙏 @cvc90

**Pull request merged**
