### PR TITLE
added backslashes to the docker run command

### PR DESCRIPTION
**Pull request by 101br03k**
added backslashes to the docker run command. 
otherwise it will not include the last couple of lines in the docker run

### CODE REVIEW

**Comment by 101br03k** [comment]
@101br03k
[Update README.md](https://github.com/jokob-sk/Pi.Alert/pull/139/commits/fcdff71c369ed323bd4b6efa4a418d7e082dff1d)
removed the last backslash otherwise a new line of docker run will come up

**Comment by 101br03k** [comment]
hmm, its still giving an error on the port part of docker run

**Comment by jokob-sk** [comment]
Hi there and happy NY!

Thanks for the PR!

I double checked, and this works fine on my end:

```yaml
docker run -d --rm --network=host --name=pialert \
  -v /volume2/docker_appdata/pialert/config:/home/pi/pialert/config \
  -v /volume2/docker_appdata/pialert/db:/home/pi/pialert/db \
  -e TZ=Europe/Berlin \
  -e PORT=20211 \
  -e TZ=Europe/Berlin \
  jokobsk/pi.alert:latest 
```
I was indeed missing the line endings, but the port is really an env variable, if you check this file, you'll see why: https://github.com/jokob-sk/Pi.Alert/blob/main/dockerfiles/start.sh

Feel free to adjust your PR and I'll accept it :)

Thanks!
j

**Comment by jokob-sk** [comment]
Hey, as I'm just about to push a new image I fixed it myself,

Thanks for reporting it!

**Pull request closed without merging**
