### PR TITLE
Futher optimizing Dockerfile

### PR DESCRIPTION
**Pull request by Macleykun**
So in this PR i prefer to set in git the right permission for users.
Technically the chmod/chgrp wouldn't be needed, but do try this out yourself first.

Somehow i couldn't get the cmd part to work as i want it, if we can change this. The container will quit way faster which is what a user would expect.

# this one needs proper testing!!! interms of read/write to db and how default permissions effect on new machines (both with and withoud git clone)

### CODE REVIEW

**Comment by jokob-sk** [comment]
Hi! Thanks for the hard work. I really like how you cleaned up the CMD command, much nicer now :)

The container builds fine for all platforms, however when testing the app it seems like the DB is read only. Here is a screenshot:

Also there seems to be some test data (see router name) - not sure if this is some issue on my end?

https://i.imgur.com/rHedUSH.png

I didn't test it on other platforms yet as it's not working on Windows so I guess I'll face the same issue elsewhere. If needed I can still run the same test on my raspberry Pi if you think that would make a difference. 

I've published your PR on docker hub if you want to give the images a try: https://registry.hub.docker.com/r/jokobsk/pialert_dev

**Comment by Macleykun** [comment]
yeah i thought so, I now added that the www-data is the owner which should save us using a chmod to give it rw.
I've also restored the db, good catch forgot about that one.

Normally a .db is made automatically from code, but this works out well enough too! Can ya try this new version?

**Comment by Macleykun** [comment]
had to do some more work, so the problem is that the container runs on www-data (not root i believe?)
the problem is that we as a user, mount a volume with already data on it that is owned by us fully but not others for write to the container.
The container then using it's own OS has different UID's and such, and can't write to the db as a result.

I couldn't find anything to fix this properly, and b/c this mount happens at run, i decided to add chmod o+w so that the folder is writeable for everyone.

Not the best, but it works now.

**Comment by jokob-sk** [comment]
Hey, 

Thanks!

Seems like you dropped the `EXPOSE 80` line during the optimization process. I think at least some port needs to be exposed for this to work?

I tried adding `EXPOSE 80`  just before the `CMD` command and the image builds and runs fine, with what I can tell are correct DB permissions. It also builds on other platforms. 

Also, I use this approach to map external user IDs to some of my docker containers, can we use this approach here and will it help us solve some issues? 

https://github.com/jokob-sk/User-mapping-for-Docker (I found this script somewhere a while ago, so not my original work)

**Comment by Macleykun** [comment]
> Hey,
> 
> Thanks!
> 
> Seems like you dropped the `EXPOSE 80` line during the optimization process. I think at least some port needs to be exposed for this to work?
> 
> I tried adding `EXPOSE 80` just before the `CMD` command and the image builds and runs fine, with what I can tell are correct DB permissions. It also builds on other platforms.
> 
> Also, I use this approach to map external user IDs to some of my docker containers, can we use this approach here and will it help us solve some issues?
> 
> https://github.com/jokob-sk/User-mapping-for-Docker (I found this script somewhere a while ago, so not my original work)

Expose is actually meant for internal communication: https://we-are.bookmyshow.com/understanding-expose-in-dockerfile-266938b6a33d#:~:text=The%20EXPOSE%20instruction%20exposes%20the%20specified%20port%20and%20makes%20it%20available%20only%20for%20inter%2Dcontainer%20communication.
So, let's say you would have a mysql container and then pi.alert. Then you would add expose on the mysql container so that you don't have to publish the port to the host (which would be an unnecassry exposing a port to the public/outside).

Good to hear it's working on all platforms :)

I actually was trying to find some sort of way to let it work for all but, i think your idea is the normal way to go really.

If you want, you can modify this PR to add that in!

Meanwhile i'll look if i can change the startup script. I have a feeling that if that is changed a bit it should respond way better when closing the container. Looked a bit around and saw other projects also using a script to start everything up :) (sometimes i just want stuff to look in a certain way, even tho it doesn't matter).

**Comment by Macleykun** [comment]
sorry for all the commits
it's now stable/working tho, but i'm stumbled why the usual way of running lighthttpd doesn't work in your case.

**Comment by jokob-sk** [comment]
Cool, thanks!

Interesting about the `EXPOSE 80` command. The only thing is that the GUI
configuration tools (at least Docker for desktop on Windows) only seem
allow to mapping ports if you use the EXPOSE statement. I understand it's
not the correct thing to do, but I'd argue that for the ease of use we
leave in EXPOSE. Otherwise anyone using Docker for desktop can't run the
image properly.  Maybe I'm wrong and there is a way, but I haven't found
it. Of course you can run it via the command line, but not thru the UI of
the app.:

https://i.imgur.com/vGcpWh7.png

What do you think?

Also, the container (from what I understand) needs to run on the host, not
in bridge mode. Otherwise it's not possible to scan the host network. That
means I'd need to keep this in:

https://github.com/jokob-sk/Pi.Alert/blob/2c1e7bab141b9d3b74e24daf22e5c5ed7d9a5f7c/Dockerfile#L34

It would be great if we figured out a way how to scan the host network
without running on it though...

And I checked this command is giving me an error, so it doesn't seem to be
possible to change teh port on a container running on the host:

❯ docker run -p 6776:80 --network host  pialert_pr13
WARNING: Published ports are discarded when using host network mode

I might be completely wrong here though... you are clearly more experienced
with containers than I am so I'd be happy to be wrong :)

**Comment by Macleykun** [comment]
I'll just add in the expose just to be sure then :P 
due to the different kinds of networks, i'm pretty certain we probably need to keep using the host (unless a simalair ips/ids project does it in a different way).
i'll add that one back aswell

the warning is probably b/c docker ignores the published arg if ya do it on a host. I assume ya have that with the previous mapping aswell?

**Comment by jokob-sk** [comment]
Thanks, seems like it's building fine for all platforms and is running well on windows. I'll try to merge the changes.

**Pull request merged**
