### PR TITLE
Translation work de_de.json

### PR DESCRIPTION
**Pull request by leiweibau**
I will continue later

### CODE REVIEW

**Comment by leiweibau** [comment]
You can take over the pull request for now, as I will certainly not be continuing in the next few days. When I have a bit more time, I'll open a new pull request.

Regards

**Comment by jokob-sk** [comment]
Thank you @leiweibau 🙏hope you have a great day :)

**Comment by jokob-sk** [comment]
Hey @leiweibau FYI I implemented Weblate for translations, so it's easier to contribute: https://hosted.weblate.org/projects/pialert/core/

**Comment by leiweibau** [comment]
Thanks for the info. I'll take a look at it.

**Pull request merged**
