### PR TITLE
Pi.alert new features in deviceDetails.php (tools tab) and new translations

### PR DESCRIPTION
**Pull request by cvc90**
<h1>Pull Request</h1>
<h2>Changes</h2>
<h3>Update deviceDetails.php (front/)</h3>

- Added new option "Test Ping" in "Tools"
- Added new translation variable (<?= lang('DevDetail_Tools_Ping_Start');?>)
- Added new function "Traceroute" in "Tools"
- Added new function "nslookup" in "Tools"
- Added new function "Mtr" in "Tools"
- Added new icon in function "Nmap" in "Tools"
- Added translation variable "DevDetail_Spinner"
- Added translation variable "DevDetail_Loading"
- Added "DevDetail_Loading" translation variable in various sections
- Added a new option "WOL" in "Tools"
- Added translation variable "DevDetail_Tab_Tools_WOL_Title"
- Added translation variable "DevDetail_Tab_Tools_WOL_Start"
- Added new function "Internet Info" in "Tools"
- Added icon in function "Speedtest"
- Added "Nmap" tab
- Added "Nmap" in the content of the "Nmap" tab
- Updated "Speedtest" function
- Updated translation variable "DevDetail_Tab_Tools_Ping_Title"
- Updated translation variable "DevDetail_Tab_Tools_Ping_Start"
- Updated "tab control" (Now it will always be the "Tools" tab instead of "Nmap")
- Updated id of the "Ping" function
- Updated "WOL" section so that it is only visible if the device does not have mac (mac="Internet")
- Updated "MTR" section so that it is only visible if the device does not have mac (mac="Internet")
- Updated "Nslookup" section so that it is only visible if the device does not have mac (mac="Internet")
- Updated "Traceroute" section so that it is only visible if the device does not have mac (mac="Internet")
- Updated "Ping" section so that it is only visible if the device does not have mac (mac="Internet")
- Updated "WOL" section so that it is only visible if the device does not have a mac (mac="Internet")
- Updated "MTR" section so that it is only visible if the device does not have a mac (mac="Internet")
- Updated "Nslookup" section so that it is only visible if the device does not have a mac (mac="Internet")
- Updated "Traceroute" section so that it is only visible if the device does not have a mac (mac="Internet")
- Updated "Ping" section so that it is only visible if the device does not have a mac (mac="Internet")
- Updated "Nmap" tab (Only shown in case the mac is not "Internet")
- Update target from "panTools" to "panNmap" for function loadNmap();
- Removed "Nmap" in the content of the "Tools" tab
- Removed blank spaces

<h3>Create ping.php (front/php/server/)</h3>

- File is created to perform "ping" functions
- Updated command in variable "$output"
- Updated translation variable
- Update banner creators
- Updated error message style
- Added new comments to facilitate development
- Optimized white spaces
- Optimized style

<h3>Create traceroute.php (front/php/server/)</h3>

- File is created to perform "traceroute" functions

<h3>Create nslookup.php (front/php/server/)</h3>

- File is created to perform "nslookup" functions

<h3>Create mtr.php (front/php/server/)</h3>

- File is created to perform "mtr" functions

<h3>Create wol.php (front/php/server/)</h3>

- File is created to perform "wol" functions
- Disable password validation check

<h3>Create internetinfo.php (front/php/server/)</h3>

- File is created to perform "internet info" functions
- Added new function to check if there is an error

<h3>Update Dockerfile</h3>

- Added to the installation line the package "iputils-ping"
- Added to the installation line the package "traceroute"

<h3>Update en_us.json (front/php/templates/language/)</h3>

- Added translation variable "DevDetail_Tab_Tools_Ping_Title"
- Added translation variable "DevDetail_Tab_Tools_Ping_Start"
- Added translation variable "DevDetail_Tab_Tools_Ping_Error"
- Added translation variable "DevDetail_Tab_Tools_Traceroute_Title"
- Added translation variable "DevDetail_Tab_Tools_Traceroute_Start"
- Added translation variable "DevDetail_Tab_Tools_Traceroute_Error"
- Added translation variable "DevDetail_Tab_Tools_Nslookup_Title"
- Added translation variable "DevDetail_Tab_Tools_Nslookup_Start"
- Added translation variable "DevDetail_Tab_Tools_Nslookup_Error"
- Added translation variable "DevDetail_Tab_Tools_Mtr_Title"
- Added translation variable "DevDetail_Tab_Tools_Mtr_Start"
- Added translation variable "DevDetail_Tab_Tools_Mtr_Error"
- Added translation variable "DevDetail_Loading"
- Added translation variable "DevDetail_Tab_Tools_WOL_Title"
- Added translation variable "DevDetail_Tab_Tools_WOL_Start"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error_MAC"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error_Port"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error_Password"
- Added translation variable "DevDetail_Tab_Tools_WOL_Message"
- Added translation variable "DevDetail_Tab_Internet_Speedtest_Title"
- Added translation variable "DevDetail_Tab_Internet_Speedtest_Start"
- Added translation variable "DevDetail_Tab_Internet_Speedtest_Error"
- Added translation variable "DevDetail_Tab_Internet_Info_Title"
- Added translation variable "DevDetail_Tab_Internet_Info_Start"
- Added translation variable "DevDetail_Tab_Internet_Info_Error"

<h3>Update es_es.json (front/php/templates/language/)</h3>

- Added translation variable "DevDetail_Tab_Tools_Ping_Title"
- Added translation variable "DevDetail_Tab_Tools_Ping_Start"
- Added translation variable "DevDetail_Tab_Tools_Ping_Error"
- Added translation variable "DevDetail_Tab_Tools_Traceroute_Title"
- Added translation variable "DevDetail_Tab_Tools_Traceroute_Start"
- Added translation variable "DevDetail_Tab_Tools_Traceroute_Error"
- Added translation variable "DevDetail_Tab_Tools_Nslookup_Title"
- Added translation variable "DevDetail_Tab_Tools_Nslookup_Start"
- Added translation variable "DevDetail_Tab_Tools_Nslookup_Error"
- Added translation variable "DevDetail_Tab_Tools_Mtr_Title"
- Added translation variable "DevDetail_Tab_Tools_Mtr_Start"
- Added translation variable "DevDetail_Tab_Tools_Mtr_Error"
- Added translation variable "DevDetail_Loading"
- Added translation variable "DevDetail_Tab_Tools_WOL_Title"
- Added translation variable "DevDetail_Tab_Tools_WOL_Start"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error_MAC"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error_Port"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error_Password"
- Added translation variable "DevDetail_Tab_Tools_WOL_Message"
- Added translation variable "DevDetail_Tab_Internet_Speedtest_Title"
- Added translation variable "DevDetail_Tab_Internet_Speedtest_Start"
- Added translation variable "DevDetail_Tab_Internet_Speedtest_Error"
- Added translation variable "DevDetail_Tab_Internet_Info_Title"
- Added translation variable "DevDetail_Tab_Internet_Info_Start"
- Added translation variable "DevDetail_Tab_Internet_Info_Error"

<h3>Update de_de.json (front/php/templates/language/)</h3>

- Added translation variable "DevDetail_Tab_Tools_Ping_Title"
- Added translation variable "DevDetail_Tab_Tools_Ping_Start"
- Added translation variable "DevDetail_Tab_Tools_Ping_Error"
- Added translation variable "DevDetail_Tab_Tools_Traceroute_Title"
- Added translation variable "DevDetail_Tab_Tools_Traceroute_Start"
- Added translation variable "DevDetail_Tab_Tools_Traceroute_Error"
- Added translation variable "DevDetail_Tab_Tools_Nslookup_Title"
- Added translation variable "DevDetail_Tab_Tools_Nslookup_Start"
- Added translation variable "DevDetail_Tab_Tools_Nslookup_Error"
- Added translation variable "DevDetail_Tab_Tools_Mtr_Title"
- Added translation variable "DevDetail_Tab_Tools_Mtr_Start"
- Added translation variable "DevDetail_Tab_Tools_Mtr_Error"
- Added translation variable "DevDetail_Loading"
- Added translation variable "DevDetail_Tab_Tools_WOL_Title"
- Added translation variable "DevDetail_Tab_Tools_WOL_Start"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error_MAC"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error_Port"
- Added translation variable "DevDetail_Tab_Tools_WOL_Error_Password"
- Added translation variable "DevDetail_Tab_Tools_WOL_Message"
- Added translation variable "DevDetail_Tab_Internet_Speedtest_Title"
- Added translation variable "DevDetail_Tab_Internet_Speedtest_Start"
- Added translation variable "DevDetail_Tab_Internet_Speedtest_Error"
- Added translation variable "DevDetail_Tab_Internet_Info_Title"
- Added translation variable "DevDetail_Tab_Internet_Info_Start"
- Added translation variable "DevDetail_Tab_Internet_Info_Error"

### CODE REVIEW

**Comment by jokob-sk** [comment]
Hey @cvc90 
Thanks for the great work!
Ideally I want the tools to be executable per device and integrated into the existing functionality (e.g. Run action on device). 

If we keep extending the UI the app will be hard to maintain. 

For example as mentioned, there is already WOL functionality in the APP so why would we need another WOL tool?

This PR is getting quite big and not sure if I can review/approve it. If I approve it I would have to rewrite the WOL code and look into how to pre-populate MAC selection etc. < can you have a look at this?

Going forward, it would be nice to keep PR requests smaller so I can adjust and review where needed. 

An alternative is to move out the Tools from Device Details. It seems like the tools are not related to the devices so in that case, we could move it into maintenance. In general the deviceDetails file is growing too big to maintain so I'm thinking of breaking it down and moving functionality not related to devices somewhere else.

**Comment by cvc90** [comment]
Hi @jokob-sk!

All these tools are executable for each device, the result will vary depending on the device from which the test is performed.

Some of these tools are not available depending on the type of device.

It has not been wanted to integrate with any other functionality because I see it absurd that these tests are carried out constantly, since they will only be done in a timely manner.

With what you say that the WOL functionality already exists, I will review to merge it and not have them duplicated, but I will tell you that the added functionality is very basic, simply by means of a get request with the device's mac, the WOL request is sent.

If the PR has many small changes and I make it seem bigger than it really is.

Not only in the future... I always try to keep the PR as clear and simple as possible. (But this one is a bit exceptional)

I don't think removing it from Tools is the most appropriate, since as I told you before, when you launch any of the options added in "Tools" it will only give you the result on the current device.

Perhaps in the future with a more complete tool that would be able to save the results obtained... or perhaps converting it to a plugin would make more sense for it to be in another place.

**Comment by jokob-sk** [comment]
Alright, I'll trust you 👍 let me know once you review the WOL functionality and I'll merge it in. If needed I can always adjust the code later if needed. Thanks for considering my comments.

**Comment by jokob-sk** [comment]
Hi @cvc90 !

I had a look at this PR and I don't see reason why all the Tools can't  be added under this dropdown, since there is no user input needed:

image

**Comment by cvc90** [comment]
As soon as I can divide the PR and update with the new changes requested.

**Pull request merged**
