### PR TITLE
enable unifi scanner to show online state of devices

### PR DESCRIPTION
**Pull request by tuhriel**
The Unifi Import will now check if a device is online or not. To do this it performs now two calls to the unifi controller get_clients() and get_users() and updates the "Watched_Value_4" accordingly
also it now pulls the correct "last known IP" and connected network
I further added some logging functionality to the script

### CODE REVIEW

**Comment by jokob-sk** [comment]
Thanks so much 🙏- can you have a look and test this if possible as there has been another PR at the same time as yours for the UNIFI plugin? The more eyes the better.

**Comment by tuhriel** [comment]
Just had it run for a moment and there seems something up... I hope I can dig a bit deeper this evening

**Comment by jokob-sk** [comment]
Thanks, much appreciated 👍

**Comment by tuhriel** [comment]
ok, it seems there are some other UI glitches ("New Device" tick and "Last IP" not showing in the device details) which I suppose are not related to my change. 
But there is also a bad side effect from my script. it now shows a lot of devices which are not online as online, due to the way the data is imported into the 'DHCP_Leases' table.
probably need to acutally write it into the 'Current Scan' table like the 'arp scan' and 'pihole sync'

not sure how fast I can do that, alternatively I can change to only 'export' the currently online devices instead of all.

**Comment by jokob-sk** [comment]
Thanks @tuhriel for looking into this!
Mapping the data to the CurrentScan table should resolve the issue. It was in the back of my mind to have a look at that, because that was not possible in previous versions. The change should be relatively straight forward - needing only to map the table in the config.JSON. That being said - everything in the CurrentScan table is treated as online - not sure how much of an issue - I can work on adding the Online status into the CurrentScan table too and then adjusting how online/offline devices are reported (not sure if in this release - I already did a lot of rewrites). An alternative is to do an initial import and scan as two separate plugins, but that sounds overkill. Or maybe a setting so the user can specify what's imported and they can adjust the settings after the initial import - this might be actually the simplest solution for now.

Thanks again for spending time on this project, appreciate it

**Comment by tuhriel** [comment]
I created a PR (#403 ) for a small hotfix to only provide online devices.

I like the idea with the initial import via the config. 
As soon as I get the time I'll update the script to write to CurrentScan and give the user the option for a for a full  import

**Comment by jokob-sk** [comment]
Thanks @tuhriel 🙏merged it - I see the mapping is already pointing to the CurrentScan table so this should work as v0.1 - thanks for helping out!

**Pull request merged**
