### PR TITLE
fix: github packages 403

### PR DESCRIPTION
**Pull request by sbe-arg**
@jokob-sk :man_facepalming:

### CODE REVIEW

**Comment by sbe-arg** [comment]
:grimacing: no words when github doesn't let me test this in the fork I hope github allows this to be dynamic... the problem is that the owner/repository need to be lower case so some form of tolower:${{env var}} is required for this to work on forks wich I dont know if is possible inside the docker build action

**Comment by sbe-arg** [comment]
Ill check back again after is merged if there is any further permission issues.

**Comment by jokob-sk** [comment]
all good, we don't develop enterprise software here lol :D - I really appreciate all the help I can get, thanks @sbe-arg 💛

**Comment by sbe-arg** [comment]
@jokob-sk it worked as expected https://github.com/jokob-sk/Pi.Alert/pkgs/container/pi.alert

**Pull request merged**
