### PR TITLE
Split it up

### PR DESCRIPTION
**Pull request by Data-Monkey**
Sorry Jakob, I thnk I have exceeded my git skills.
I don't seem to be able to resolve some conflicts. 
Maybe you can help or I will try a bit more...

### CODE REVIEW

**Comment by Data-Monkey** [comment]
I have removed pialert.py from my code and made it __main__.py

**Comment by jokob-sk** [comment]
I'm exceeding my git skills almost every time I commit so no worries. 😁

I'm aiming to get to this over the weekend. Thanks again for the great help!

**Comment by Data-Monkey** [comment]
this is not a finished version, but would be good to have someone else have a good look

**Comment by jokob-sk** [comment]
Yeah, I'll try to merge it and I'll test it out on my setup with the test cased discussed previously. I'm not aiming to do a release for at least one or two weeks during which I can test if everything is OK. This way I can have at least a _dev docker image build that someone might want to test.

**Pull request merged**
